name: CI

on: [push, workflow_dispatch]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Packaging, Verifying and Publishing
        run: echo "Package phase completed"

  registry-1:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Distributing to DockerHub
        run: echo "Distribution to DockerHub completed"

  registry-2:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Distributing to Artifactory
        run: echo "Distribution to Artifactory completed"
